'use strict';
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=x=>Number.isFinite(x)?x.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const pct=x=>Number.isFinite(x)?`${(x*100).toFixed(2)}%`:'—', price=x=>Number.isFinite(x)?x.toFixed(3):'—';
let data, symbol='510880', range='66', page='market', records=[], storageOK=true;
const STORE='hongli-pages-records-v1';
function table(headers,rows){return rows.length?`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<p class="empty">当前没有可展示的记录。</p>';}
function summary(items){return items.map(([k,v])=>`<div><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`).join('');}
function csv(name,headers,rows){const cell=x=>{let s=String(x??'');if(/^[=+@\-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const url=URL.createObjectURL(new Blob(['\ufeff'+[headers,...rows].map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function state(row){if(!row||![row.close,row.ma,row.upper_band,row.lower_band,row.position].every(Number.isFinite))return null;const channel=row.upper_band === row.lower_band ? 0.5 :(row.close-row.lower_band)/(row.upper_band-row.lower_band);const lower=(row.close-row.lower_band)/row.close,upper=(row.upper_band-row.close)/row.close;return {channel,label:lower<0?'触发买入/加仓':upper<0?'触发卖出/减仓':'通道内观察',hint:lower<0?'价格已跌破下轨，检查分批买入条件。':upper<0?'价格已突破上轨，检查减仓条件。':lower<upper?`更接近下轨，距触发价约 ${pct(lower)}。`:`更接近上轨，距触发价约 ${pct(upper)}。`};}
const plotConfig={responsive:true,displaylogo:false,scrollZoom:false,modeBarButtonsToRemove:['select2d','lasso2d']};
function renderMarket(){if(!data)return;const asset=data.assets[symbol],all=asset.rows,latest=all.at(-1),status=state(latest);let rows=range==='custom'?all.filter(r=>r.date>=$('range-start').value&&r.date<=$('range-end').value):Number(range)?all.slice(-Number(range)):all;
$('instrument').innerHTML=`<div><span class="eyebrow">${symbol} · 场内 ETF</span><h1>${esc(asset.profile.name)}</h1><small>日线截至 ${latest.date}</small></div><div class="price">${price(latest.close)}<small>日线收盘 / 元</small></div><div class="stat"><span class="eyebrow">通道状态</span><strong>${status?.label||'等待计算'}</strong></div><div class="stat"><span class="eyebrow">日线目标仓位</span><strong>${Number.isFinite(latest.position)?Math.round(latest.position*100)+'%':'—'}</strong></div>`;
$('custom-range').hidden=range!=='custom';document.querySelectorAll('[data-range]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.range===range)));
if(!rows.length){$('chart-caption').textContent='当前选择区间没有行情，请调整起止日期。';Plotly.purge('chart');$('decisions').innerHTML='';$('decision-date').textContent='';return;}
const last=rows.at(-1),s=state(last),vol=$('volume').checked,dates=rows.map(r=>r.date);
$('chart-caption').textContent=`${data.source} · ${data.price_basis} · ${asset.profile.window} 日 / ${asset.profile.num_std} 倍标准差 · ${rows[0].date} 至 ${last.date} · ${rows.length} 个交易日`;
const traces=$('chart-type').value==='candlestick'?[{type:'candlestick',x:dates,open:rows.map(r=>r.open),close:rows.map(r=>r.close),high:rows.map(r=>r.high),low:rows.map(r=>r.low),name:'K线',increasing:{line:{color:'#be3e47'}},decreasing:{line:{color:'#188568'}}}]:[{x:dates,y:rows.map(r=>r.close),name:'收盘价',line:{color:'#17212b',width:2}}];
traces.push({x:dates,y:rows.map(r=>r.upper_band),name:'上轨',line:{color:'#6b8bc5',width:1,dash:'dash'}},{x:dates,y:rows.map(r=>r.lower_band),name:'下轨',line:{color:'#6b8bc5',width:1,dash:'dash'},fill:'tonexty',fillcolor:'rgba(75,113,182,.055)'},{x:dates,y:rows.map(r=>r.ma),name:'中轨',line:{color:'#6b8bc5',width:1}});
for(const [sign,name,color,marker] of [[1,'加仓','#be3e47','triangle-up'],[-1,'减仓','#188568','triangle-down']]){const points=rows.filter(r=>sign*r.signal>0);traces.push({x:points.map(r=>r.date),y:points.map(r=>sign>0?r.low*.99:r.high*1.01),name,mode:'markers',marker:{color,size:9,symbol:marker}});}
if(vol)traces.push({x:dates,y:rows.map(r=>r.volume),type:'bar',name:'成交量',yaxis:'y2',marker:{color:rows.map(r=>r.close>=r.open?'#be3e47':'#188568')}});
Plotly.react('chart',traces,{margin:{l:8,r:55,t:32,b:28},font:{size:11,color:'#657381'},paper_bgcolor:'#fff',plot_bgcolor:'#fff',xaxis:{rangeslider:{visible:false},tickformat:'%m/%d',rangebreaks:[{bounds:['sat','mon']}],showgrid:false,anchor:vol?'y2':'y'},yaxis:{domain:vol?[.28,1]:[0,1],side:'right',tickformat:'.3f',gridcolor:'#eff2f6'},yaxis2:{domain:[0,.2],side:'right',gridcolor:'#eff2f6'},legend:{orientation:'h',x:1,xanchor:'right',y:1.12},hovermode:'x unified',dragmode:'pan',uirevision:`${symbol}:${range}:${dates[0]}:${last.date}`},plotConfig);
$('decision-date').textContent=`按图表末日 ${last.date} 计算`;if(!s){$('decisions').innerHTML='<p class="empty">行情不足以计算布林通道。</p>';return;}
const previous=all.filter(r=>r.date<=last.date&&r.signal).at(-1);
$('decisions').innerHTML=`<section><span class="eyebrow">01 / 当前位置</span><h3>${s.label}</h3><p>${s.hint}</p><p>通道位置 ${Math.round(s.channel*100)}%</p></section><section><span class="eyebrow">02 / 价格边界</span><div class="bands">${[['下轨',last.lower_band],['中轨',last.ma],['上轨',last.upper_band]].map(([n,v])=>`<div><small>${n}</small><strong>${price(v)}</strong></div>`).join('')}</div><p>与当日收盘价比较，观察买入与卖出边界。</p></section><section><span class="eyebrow">03 / 最近调仓</span><h3>${previous?previous.date+' · '+(previous.signal>0?'加仓':'减仓'):'暂无调仓'}</h3><p>${previous?'调仓后目标仓位 '+Math.round(previous.position*100)+'%':'当前区间尚未出现调仓信号。'}</p><p>策略信号，请结合实际持仓判断。</p></section>`;}
function signalRows(){return Object.entries(data.assets).flatMap(([id,a])=>a.rows.filter(r=>r.signal).map(r=>({...r,symbol:id,name:a.profile.name}))).filter(r=>($('signal-symbol').value==='all'||r.symbol===$('signal-symbol').value)&&($('signal-side').value==='all'||(r.signal>0?'buy':'sell')===$('signal-side').value)).sort((a,b)=>b.date.localeCompare(a.date));}
const signalHeaders=['日期','ETF','名称','方向','仓位变化','目标仓位','收盘价','下轨','上轨','来源','价格口径'];
const signalCells=r=>[r.date,r.symbol,r.name,r.signal>0?'加仓':'减仓',pct(r.signal),pct(r.position),price(r.close),price(r.lower_band),price(r.upper_band),data.source,data.price_basis];
function renderSignals(){if(!data)return;const rows=signalRows();$('signal-summary').innerHTML=summary([['调仓信号',rows.length],['加仓次数',rows.filter(r=>r.signal>0).length],['减仓次数',rows.filter(r=>r.signal<0).length]]);$('signal-table').innerHTML=table(signalHeaders,rows.map(signalCells));}
function renderResearch(){if(!data)return;const a=data.assets[$('research-symbol').value],m=$('research-metric').value,rows=a.optimization.filter(r=>Number.isFinite(r[m])),p=m!=='Sharpe Ratio',fmt=x=>p?pct(x):x.toFixed(2);if(!rows.length){$('research-summary').textContent='当前数据无法计算参数结果。';Plotly.purge('heatmap');return;}const best=rows.reduce((a,b)=>b[m]>a[m]?b:a),windows=[...new Set(rows.map(r=>r.window))].sort((a,b)=>a-b),stds=[...new Set(rows.map(r=>r.num_std))].sort((a,b)=>a-b),z=stds.map(s=>windows.map(w=>rows.find(r=>r.window===w&&r.num_std===s)?.[m]??null));$('research-summary').innerHTML=summary([['区间内最优周期',best.window],['区间内最优标准差',best.num_std],[$('research-metric').selectedOptions[0].text,fmt(best[m])]]);$('research-scope').textContent=`${a.rows[0].date} 至 ${a.rows.at(-1).date} · ${data.price_basis} · 首批仓位 ${pct(a.profile.first_batch_pct)} · 深度阈值 2% · ${rows.length} 组参数`;Plotly.react('heatmap',[{type:'heatmap',x:windows,y:stds,z,colorscale:'Blues',text:z.map(r=>r.map(x=>x===null?'':fmt(x))),texttemplate:innerWidth>600?'%{text}':undefined,colorbar:{tickformat:p?'.0%':'.1f'},hovertemplate:'周期 %{x}<br>标准差 %{y}<br>%{text}<extra></extra>'}],{margin:{l:48,r:50,t:20,b:45},xaxis:{title:{text:'布林周期'}},yaxis:{title:{text:'标准差倍数'}},font:{size:11,color:'#657381'}},plotConfig);}
function validRecord(r){return r&&/^\d{4}-\d{2}-\d{2}$/.test(r.date)&&!Number.isNaN(Date.parse(r.date))&&new Date(r.date).toISOString().slice(0,10)===r.date&&['510880','512890'].includes(r.symbol)&&['buy','sell'].includes(r.side)&&Number.isSafeInteger(r.quantity)&&r.quantity>0&&Number.isFinite(r.price)&&r.price>0&&Number.isFinite(r.quantity*r.price+r.fee)&&Number.isFinite(r.fee)&&r.fee>=0&&typeof r.note==='string'&&r.note.length<=200;}
function portfolio(list){const lots={'510880':[],'512890':[]};let realized=0,capital=0;for(const r of list.map((r,i)=>({...r,i})).sort((a,b)=>a.date.localeCompare(b.date)||a.i-b.i)){if(!validRecord(r))throw Error('浏览器中的记录格式无效，未覆盖原数据。');if(r.side==='buy'){const cost=r.quantity*r.price+r.fee;capital+=cost;lots[r.symbol].push({quantity:r.quantity,cost});}else{let quantity=r.quantity,cost=0;const queue=lots[r.symbol];if(queue.reduce((s,l)=>s+l.quantity,0)<quantity)throw Error('卖出份额超过该日期已记录的持仓。');while(quantity>0){const lot=queue[0],take=Math.min(quantity,lot.quantity),part=lot.cost*take/lot.quantity;cost+=part;lot.cost-=part;lot.quantity-=take;quantity-=take;if(!lot.quantity)queue.shift();}realized+=r.quantity*r.price-r.fee-cost;}}const positions=Object.entries(lots).map(([symbol,queue])=>{const quantity=queue.reduce((s,l)=>s+l.quantity,0),cost=queue.reduce((s,l)=>s+l.cost,0),last=data.assets[symbol].rows.at(-1).close;return{symbol,quantity,cost,last,value:quantity*last,pnl:quantity*last-cost};}).filter(p=>p.quantity);return{positions,realized,capital,value:positions.reduce((s,p)=>s+p.value,0),unrealized:positions.reduce((s,p)=>s+p.pnl,0)};}
function renderPortfolio(){if(!data)return;try{const p=portfolio(records);$('portfolio-summary').innerHTML=summary([['当前市值',money(p.value)],['浮动收益',money(p.unrealized)],['已实现收益',money(p.realized)],['记录笔数',records.length]]);$('positions').innerHTML=table(['ETF','份额','成本','参考收盘价','市值','浮动收益'],p.positions.map(r=>[r.symbol,r.quantity,money(r.cost),price(r.last),money(r.value),money(r.pnl)]));$('record-list').innerHTML=table(['日期','ETF','方向','份额','成交价','费用','备注'],records.slice().reverse().map(recordCells));}catch(e){storageOK=false;$('record-message').textContent=e.message;}$('add-record').disabled=!storageOK;}
const recordCells=r=>[r.date,r.symbol,r.side==='buy'?'买入':'卖出',r.quantity,price(r.price),money(r.fee),r.note];
function render(){if(!data)return;({market:renderMarket,portfolio:renderPortfolio,signals:renderSignals,research:renderResearch})[page]();}
function navigate(next){page=['market','portfolio','signals','research'].includes(next)?next:'market';document.querySelectorAll('.page').forEach(el=>el.hidden=el.id!==page);document.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-current',b.dataset.page===page?'page':'false'));history.replaceState(null,'','#'+page);render();}
async function load(){try{$('refresh').disabled=true;const response=await fetch('./market.json',{cache:'no-store'});if(!response.ok)throw Error();const next=await response.json();if(next.schema!==1||!next.assets?.['510880']?.rows?.length||!next.assets?.['512890']?.rows?.length)throw Error();data=next;const stale=(Date.now()-Date.parse(data.data_as_of+'T16:00:00+08:00'))/86400000>7;$('notice').textContent=stale?`行情截至 ${data.data_as_of}，已超过 7 天。当前展示最近一次可用数据。`:'';$('source').textContent=`${data.source} · ${data.price_basis} · 行情截至 ${data.data_as_of}`;$('info-content').innerHTML=`<p>${esc(data.source)} · ${esc(data.price_basis)}</p><p>行情截至 ${esc(data.data_as_of)} · 页面构建 ${esc(data.built_at)}</p>`+Object.values(data.assets).map(a=>`<p>${a.profile.symbol}：${a.profile.window} 日 / ${a.profile.num_std} 倍标准差 / 首批仓位 ${pct(a.profile.first_batch_pct)}</p>`).join('');const a=data.assets[symbol].rows;if(!$('range-start').value)$('range-start').value=a.at(-66)?.date||a[0].date;if(!$('range-end').value)$('range-end').value=a.at(-1).date;render();}catch(e){$('notice').textContent=data?'更新暂不可用，继续显示已加载行情。':'行情加载失败，请稍后点击“检查更新”重试。';}finally{$('refresh').disabled=false;}}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));document.querySelectorAll('[data-symbol]').forEach(b=>b.onclick=()=>{symbol=b.dataset.symbol;document.querySelectorAll('[data-symbol]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderMarket();});document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{range=b.dataset.range;renderMarket();});for(const id of ['chart-type','volume','range-start','range-end'])$(id).onchange=renderMarket;for(const id of ['signal-symbol','signal-side'])$(id).onchange=renderSignals;for(const id of ['research-symbol','research-metric'])$(id).onchange=renderResearch;
$('refresh').onclick=load;$('data-info').onclick=()=>$('info-dialog').showModal();$('add-record').onclick=()=>{$('form-error').textContent='';$('record-form').elements.date.value=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());$('record-dialog').showModal();};$('close-record').onclick=()=>$('record-dialog').close();$('record-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),r={date:f.get('date'),symbol:f.get('symbol'),side:f.get('side'),quantity:Number(f.get('quantity')),price:Number(f.get('price')),fee:Number(f.get('fee')),note:String(f.get('note')).trim()};try{if(!storageOK||!validRecord(r))throw Error('请填写有效的成交日期、价格和份额。');portfolio([...records,r]);localStorage.setItem(STORE,JSON.stringify([...records,r]));records.push(r);$('record-dialog').close();e.target.reset();renderPortfolio();}catch(error){$('form-error').textContent=error.message||'当前浏览器无法保存记录。';}};
$('export-records').onclick=()=>csv('investment_records.csv',['日期','ETF','方向','份额','成交价','费用','备注'],records.map(recordCells));$('export-signals').onclick=()=>csv('bollinger_signals.csv',signalHeaders,signalRows().map(signalCells));$('export-research').onclick=()=>{const id=$('research-symbol').value,a=data.assets[id];csv(`${id}_optimization.csv`,['ETF','周期','标准差','总收益率','夏普比率','最大回撤','来源','价格口径','开始日期','结束日期'],a.optimization.map(r=>[id,r.window,r.num_std,r['Total Return'],r['Sharpe Ratio'],r['Max Drawdown'],data.source,data.price_basis,a.rows[0].date,a.rows.at(-1).date]));};
try{const saved=localStorage.getItem(STORE);records=saved?JSON.parse(saved):[];if(!Array.isArray(records)||!records.every(validRecord))throw Error();}catch(e){storageOK=false;$('record-message').textContent='无法安全读取浏览器记录，录入已停用，原数据未覆盖。';}navigate(location.hash.slice(1));load();
